services:
    - type: web
    name: orion-bot-v1-5-0
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app_v1.5.0.py
    envVars:
            - key: TELEGRAM_TOKEN
        sync: false
            - key: WEBHOOK_URL
        fromService:
          type: web
          name: orion-bot-v1-5-0
          property: host
